
version: "2.1"

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: relman

    relaciones:
        build: ./relaciones
        links:
            - mysql
        ports:
            - "8443:8443"
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://sql/relman?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 12345